# Staging Environment Configuration
# This file contains non-sensitive staging settings
# Sensitive keys should be in .env.staging files or environment variables

# Service Configuration
services:
  auth_service:
    host: "0.0.0.0"
    port: 8001
    log_level: "INFO"
    
  file_service:
    host: "0.0.0.0"
    port: 8002
    log_level: "INFO"
    
  chat_service:
    host: "0.0.0.0"
    port: 8003
    log_level: "INFO"
    
  collection_service:
    host: "0.0.0.0"
    port: 8004
    log_level: "INFO"
    
  mcp_orchestrator:
    host: "0.0.0.0"
    port: 8005
    log_level: "INFO"

# Database Configuration (non-sensitive parts)
database:
  host: "${DB_HOST}"  # From environment
  port: "${DB_PORT}"
  name: "advanced_rag_staging"
  pool_size: 20
  max_overflow: 30
  echo: false

# Redis Configuration (non-sensitive parts)
redis:
  host: "${REDIS_HOST}"  # From environment
  port: "${REDIS_PORT}"
  db: 0
  decode_responses: true

# Vector Database Configuration
qdrant:
  host: "${QDRANT_HOST}"  # From environment
  port: "${QDRANT_PORT}"
  grpc_port: "${QDRANT_GRPC_PORT}"
  timeout: 30

# CORS Configuration
cors:
  origins:
    - "https://staging.yourapp.com"
    - "https://staging-admin.yourapp.com"
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  headers: ["*"]
  credentials: true

# LLM Configuration (non-sensitive parts)
llm:
  default_provider: "openai"
  default_model: "gpt-4"
  default_embedding_model: "text-embedding-3-small"
  timeout: 60
  max_retries: 3

# Chat Configuration
chat:
  max_conversation_history: 50
  max_context_tokens: 8000
  default_top_k: 5
  stream_chunk_size: 1024

# RAG Configuration
rag:
  context_merge_strategy: "enhanced_rrf"
  rrf_k: 60.0
  diversity_penalty: 0.1
  max_chunks_per_collection: 10

# Collection Configuration
collections:
  max_per_user: 50  # Reduced for staging
  max_documents_per_collection: 5000
  max_versions: 25
  default_chunking_strategy: "recursive"
  default_chunk_size: 1000
  default_chunk_overlap: 200

# MCP Configuration
mcp:
  enable_tool_execution: true
  tool_execution_timeout: 30
  max_concurrent_executions: 5  # Reduced for staging
  enable_sandboxing: true
  execution_environment: "docker"
  docker_image: "python:3.13-slim"
  docker_network: "bridge"

# Security Configuration (non-sensitive parts)
security:
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  password_min_length: 8
  max_login_attempts: 5
  lockout_duration_minutes: 15

# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_minute: 60  # More restrictive than dev
  burst_size: 10

# Monitoring
monitoring:
  enable_metrics: true
  enable_tracing: true
  log_requests: true
  log_responses: false

# File Processing
file_processing:
  max_file_size_mb: 50  # Smaller than prod
  allowed_extensions:
    - ".pdf"
    - ".txt"
    - ".docx"
    - ".md"
    - ".csv"
    - ".json"
  temp_dir: "/app/temp/uploads"
  cleanup_interval_hours: 12 